application:
  port: 8000
  hmac_secret: "EB19D5AB6826C056004D9FC58F1EBD459D8CEBA6BB6EF736AD5B5543B528FB4D"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "dc23dcf7-4a58-4204-b593-8818629b654e"
  timeout_millisecods: 10000
